"""initial schema: letters and templates

Revision ID: ac9a0f2248b6
Revises: 
Create Date: 2026-08-02 09:22:03.041728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9a0f2248b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('from_name', sa.String(length=128), nullable=False),
    sa.Column('to_name', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('song_id', sa.String(length=128), nullable=True),
    sa.Column('song_title', sa.String(length=256), nullable=True),
    sa.Column('song_artist', sa.String(length=256), nullable=True),
    sa.Column('song_preview_url', sa.String(length=512), nullable=True),
    sa.Column('delivery_method', sa.String(length=32), nullable=False),
    sa.Column('delivery_contact', sa.String(length=256), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letters_id'), 'letters', ['id'], unique=False)
    op.create_index(op.f('ix_letters_slug'), 'letters', ['slug'], unique=True)
    op.create_table('templates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('subtitle', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('experience', sa.String(length=32), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_birthday_exclusive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_letters_slug'), table_name='letters')
    op.drop_index(op.f('ix_letters_id'), table_name='letters')
    op.drop_table('letters')
    # ### end Alembic commands ###
